version: '3'
services:
  controller:
    image: linuxserver/unifi:120
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
    volumes:
      - config:/config

  backup:
    image: coaxial/tarsnapper:0.4
    restart: always
    environment:
      # must match the setting at
      # https://localhost:8443/manage/site/default/settings/backup
      BACKUP_PERIODICITY: "0 0 1 * *"
    volumes:
      - config:/source:ro
      - tarsnap_cache:/usr/local/tarsnap-cache
      - ./files/tarsnap.key:/root/tarsnap.key:ro
      - ./files/tarsnap.conf:/usr/local/etc/tarsnap.conf:ro
      - ./files/tarsnapper.conf:/etc/tarsnapper.conf:ro

volumes:
  config:
  tarsnap_cache:
